[package]
name = "scoped-sleep"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "RAII sleep"
keywords = []
categories = ["rust-patterns"]
repository = "https://github.com/openrr/scoped-sleep"

[dependencies]
